export enum WebhookEvent {
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  MESSAGE_DELIVERED = 'MESSAGE_DELIVERED',
  MESSAGE_FAILED = 'MESSAGE_FAILED',
  MMS_RECEIVED = 'MMS_RECEIVED',
  MMS_SENT = 'MMS_SENT',
  MMS_DELIVERED = 'MMS_DELIVERED',
  MMS_FAILED = 'MMS_FAILED',
  UNKNOWN_STATE = 'UNKNOWN_STATE',
  SMS_STATUS_UPDATED = 'SMS_STATUS_UPDATED',
}
